music_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
end

music_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

music_app/app/models/user.rb
class User < ApplicationRecord

  validates :email, presence: true, uniqueness: true
  validates :password_digest, presence: true
  validates :session_token, presence: true, uniqueness: true
  validates :password, length: {minimum: 6, allow_nil: true}

  after_initialize :ensure_session_token

  attr_reader :password

  def self.generate_session_token
    SecureRandom.urlsafe_base64(16)
  end

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    return nil if user.nil?
    user.is_password?(password) ? user : nil
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save!
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

end

music_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def logged_in?
    !!current_user
    # current_user.session_token == session[:session_token]
  end

  def log_in_user!(user)
    @current_user = user
    user.reset_session_token!
    session[:session_token] = user.session_token
  end

  def logout!(user)
    current_user.reset_session_token!
    session[:session_token] = nil
  end
end

music_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  helper_method :current_user, :logged_in?, :log_in_user!

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.find_by_credentials(params[:user][:email], params[:user][:password])
    if @user
      log_in_user!(@user)
      @current_user = @user
      redirect_to user_url(@user)
    else
      flash[:errors] = ["Invalid username and/or password"]
      redirect_to new_session_url
    end
  end

  def destroy
    logout!(current_user)
    redirect_to new_session_url
  end

end

music_app/app/controllers/users_controller.rb
class UsersController < ApplicationController

  helper_method :current_user, :logged_in?, :log_in_user!

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in_user!(@user)
      @current_user = @user
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    render :show
  end


  def user_params
    params.require(:user).permit(:email, :password)
  end


end

music_app/app/helpers/application_helper.rb
module ApplicationHelper

  def auth_token
  "<input type='hidden'
         name='authenticity_token'
         value='#{form_authenticity_token}'>".html_safe
  end
end

music_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MMMM!!!</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Wendy+One" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Coda+Caption:800" rel="stylesheet">
  </head>

  <body>
    <header>
    <h1>Multiple Methods of Music Management -- MMMM!!!</h1>
    </header>
    <h2><%= current_user.email if current_user %></h2>
    <!-- <section class="logins"> -->
    <% if logged_in? %>
    <form action="<%= session_url %>" method="post">
      <%= auth_token %>
      <input type="hidden" name="_method" value="delete"/>
      <input type="submit" value="Sign Out"/>
    </form>

    <%   else %>

    <a href="<%= new_session_url %>" name="login" >Sign in</a>
    <a href="<%= new_user_url %>" name="login" >Sign up</a>

    <%  end %>
    <!-- </section> -->
    <%= yield %>
  </body>
</html>

music_app/app/views/users/new.html.erb
<form action="<%= users_url %>" method="post">
  <%= auth_token %>

  Welcome to the Music app. Sign up and join below:
  <label for="email">Email address: </label>
  <input type="text" id="email" name="user[email]" value="">
  <label for="password">Password: </label>
  <input type="password" id="password" name="user[password]" value="">

  <input type="submit" value="Sign Up!">

</form>

music_app/app/views/users/show.html.erb
<h2><%= @user.email %></h2>